### ISSUE TITLE
Tuio CIient listen remote IP address and port

### ISSUE THREAD

**Issue by Ev3rlasting** [mkalten/reacTIVision#12]
Is there a way to let tuioClient listen to a remote IP address and port? 
For example like:
`TuioProcessing tuioClient = new TuioProcessing (this, "192.168.0.109", 3333)`

**Comment by mkalten** [comment]
No, since this actually works the other way around:
You'll need to specify the target IP at your TUIO tracker application (e.g. reacTIVision),
since the TUIO/UDP packets are sent from there to the TUIO client application (such as your Processing sketch). At the client side you can therefore only specify an alternative port if needed (and also configured as the target port in the TUIO tracker application. best, Martin.K
